### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by ilsordo** [ocamllabs/ocaml-multicore#66] opened 2016-10-20 14:12 UTC
I expected the following program to loop:

``` ocaml
effect Foo : (unit -> 'a)

let _ =
  match perform Foo () with
  | x -> ()
  | effect Foo k ->
     continue k (fun () -> perform Foo ())
```

Instead the effect escapes (exception Unhandled)

If I rewrite it as 

``` ocaml
effect Foo : (unit -> 'a)

let f () = perform Foo ()

let _ =
  match f () with
  | x -> ()
  | effect Foo k ->
     continue k (fun () -> perform Foo ())
```

It runs and never terminates.

**Comment by dhil** [comment] 2016-10-20 14:32
I cannot reproduce this bug with the (rather dated) effects compiler `4.02.2+local-git-4.02.2+effects` (commit: `36008b741adc201bf9b547545344507da603ae31`). However, I can reproduce it with the most recent multicore compiler `4.02.2+local-git-master` (commit: `1ddd3d8f439eff961fb868016388ea79e4fdf4c9`).

**Comment by ilsordo** [comment] 2016-10-20 14:46
I only tested on multicore. Could this be a consequence of [dd0b37c](https://github.com/ocamllabs/ocaml-multicore/commit/dd0b37c398d3dd7eabd07981a45d5d8dd8d21ea4) ?

**Comment by stedolan** [comment] 2016-10-20 15:10
@ilsordo you're right, dd0b37c is buggy. I'll fix it and add your example to the testsuite when I get a chance.

The underlying primitive `prim_alloc_stack` expects a function to run on the new stack and an argument to pass to it. By default, the function is `fun () -> BODY` where `BODY` is whatever's between `match` and `with`, and the argument is `()`. The optimisation in dd0b37c is to notice that we need not allocate a closure when `BODY` is of the form `f x` - however, this is only valid when the evaluation of `f` and `x` do not cause side-effects (e.g. by using `perform`).

**Comment by lpw25** [comment] 2016-10-20 15:26
I have a fix for this already on the typed effects branch.

**Closed** 2016-11-14 18:25 UTC
Labels: bug
