### ISSUE TITLE
Unhandled raised when two domains use single function

### ISSUE THREAD

**Issue by radekm** [ocamllabs/ocaml-multicore#7] opened 2015-05-31 12:17 UTC
The following code works as expected

```ocaml
effect Print : string -> unit

let run thunk =
  match thunk () with
  | () -> ()
  | effect (Print s) k -> print_endline s; flush stdout; continue k ()

let thunk () =
  let rec write x =
    Printf.printf "domain %d %s\n" (Domain.self ()) x;
    flush stdout;
    perform (Print x);
    Unix.sleep 1;
    write x in

  (* Same as [write]. *)
  let rec write2 x =
    Printf.printf "domain %d %s\n" (Domain.self ()) x;
    flush stdout;
    perform (Print x);
    Unix.sleep 1;
    write2 x in

  Domain.spawn (fun () -> run (fun () -> write "first"));
  write2 "second"

let () = run thunk
```

but when I remove `write2` and replace `write2 "second"` by `write "second"` then the exception `Unhandled` is raised when performing effect `Print "second"`.

**Comment by kayceesrk** [comment] 2015-06-05 09:56
@stedolan I've narrowed the problem down to issue with promoting extensible variant types to the shared heap. I believe extensible variant pattern matching works by referential equality. However, promotion of extensible variant constructor seems to make a copy instead of moving it to the major heap. Here is the code that reproduces the behavior:

```ocaml
effect Print : string -> unit

let int_of_obj_field o i : int =
  Obj.magic @@ Obj.field (Obj.repr o) i

let print_effect e =
  Printf.printf "[%d] (%x,%x)\n%!" (Domain.self ())
    (int_of_obj_field e 0) (int_of_obj_field e 1)

let run thunk =
  match thunk () with
  | () -> ()
  | effect e k ->
      match e with
      | Print s ->
          print_effect (Print s);
          print_effect e;
          print_endline s;
          continue k ()
      | _ ->
          Unix.sleep 1;
          print_effect (Print "hello2");
          print_effect e;
          Printf.printf "[%d] exception\n%!" (Domain.self ())

let rec write x = perform (Print x); Unix.sleep 3; write x

let () =
  print_effect (Print "hello1");
  run (fun () ->
    Domain.spawn (fun () -> run (fun () -> write "child"));
    Printf.printf "spawned\n";
    write "parent")
```

The output I get is

```
[0] (1000fb524,1000fe008)
spawned
[1] (85af3fd0,85aefff0)
[1] (85af3fd0,85aefff0)
child
[0] (1000fb524,1000fe114)
[0] (85af3fd0,1000fe11c)
[0] exception
```

Observe that in domain 1, the local reference to the `Print` constructor as well as the one from the effect `e` refer to the same object in the heap (1st field in the tuple). Whereas in domain 0, they are different (one in dom 0 minor and the other in major), which causes the pattern match to fail.

**Comment by lpw25** [comment] 2015-06-05 11:30
This is probably one of a number of flaws in the current implementation of promotion. Currently, promotion creates a copy of the promoted thing and then detects reads and writes to the promoted version and reroutes them. However, this causes a number of issues (for example requiring a write barrier on writes to integer fields) and we intend to switch to a different mechanism which does not create copies. There are some subtleties to implementing the new mechanism, which is why it has not been implemented yet.

**Comment by kayceesrk** [comment] 2015-06-05 11:53
Is my understanding of the issue correct? Is this specific bug an instance of the issues associated with promotion mechanism? If so, I'd like to fix this bug in the current implementation. But I'd also like to take the lead on implementing the alternate promotion mechanism (documented somewhere? perhaps not). Lets keep this issue open either way.

**Comment by lpw25** [comment] 2015-06-05 12:10
> Is my understanding of the issue correct? Is this specific bug an instance of the issues associated with promotion mechanism?

Well I haven't looked too closely, but that seems to be the case.

> If so, I'd like to fix this bug in the current implementation.

That would be a bit tricky, although it is possible. The pattern matching of extensible variants would need to use some runtime function which checked if the thing it was checking was a promoted value.

> But I'd also like to take the lead on implementing the alternate promotion mechanism 

I suggest moving this to the mailing list and looping in Stephen.

> (documented somewhere? perhaps not).

Nope, undocumented although available from either me or Stephen.

**Closed** 2015-06-09 17:26 UTC
Labels: bug
